#!/bin/bash

set -e

# Parse image name for repo name and major tag version
tagStart=$(expr index "$IMAGE_NAME" :)
repoName=${IMAGE_NAME:0:tagStart-1}

# Tag and push image with latest
echo "Tagging and pushing" ${repoName}:latest
docker tag $IMAGE_NAME ${repoName}:latest